### PR TITLE
Added option to minify html

### PR DESCRIPTION
**Pull request by suprMax**
Hi!

Thank you for the transform!

I added this small option for myself in order to make JS bundle smaller (uglify won't compress html in strings)

I thought you might want to merge it.

### CODE REVIEW

**Comment by refractalize** [comment]
thanks @suprMax, nice patch!

Can we change the `minifyHTML` option to just `minify`?

Also, would you mind writing some documentation for the option in the README.md?

**Comment by suprMax** [comment]
Basically it's directly passed to https://github.com/kangax/html-minifier so options are the same, apart from the one that initiates minify in general

**Comment by refractalize** [comment]
nice one @suprMax! in v1.1.0

**Comment by suprMax** [comment]
Awesome! Thanks for merging!

**Pull request merged**
